/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiVoiceBriefRouteImport } from './routes/api/voice-brief'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceBriefRoute = ApiVoiceBriefRouteImport.update({
  id: '/api/voice-brief',
  path: '/api/voice-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/research': typeof ResearchRoute
  '/vault': typeof VaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-brief': typeof ApiVoiceBriefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/research': typeof ResearchRoute
  '/vault': typeof VaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-brief': typeof ApiVoiceBriefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/research': typeof ResearchRoute
  '/vault': typeof VaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-brief': typeof ApiVoiceBriefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/demo'
    | '/research'
    | '/vault'
    | '/api/chat'
    | '/api/voice-brief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/demo'
    | '/research'
    | '/vault'
    | '/api/chat'
    | '/api/voice-brief'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/demo'
    | '/research'
    | '/vault'
    | '/api/chat'
    | '/api/voice-brief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DemoRoute: typeof DemoRoute
  ResearchRoute: typeof ResearchRoute
  VaultRoute: typeof VaultRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceBriefRoute: typeof ApiVoiceBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-brief': {
      id: '/api/voice-brief'
      path: '/api/voice-brief'
      fullPath: '/api/voice-brief'
      preLoaderRoute: typeof ApiVoiceBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DemoRoute: DemoRoute,
  ResearchRoute: ResearchRoute,
  VaultRoute: VaultRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceBriefRoute: ApiVoiceBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
